# .golangci.yml configuration for employee management system
version: "1"
run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - gocyclo
    - dupl
    - goconst
    - gocritic
    - misspell
    - unconvert
    - nakedret
    - prealloc
    - stylecheck
    - revive
    - forbidigo
  settings:
    gocyclo:
      min-complexity: 10

    dupl:
      threshold: 100

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    revive:
      severity: warning
      confidence: 0.8
      rules:
        - name: indent-error-flow
          severity: warning
        - name: var-naming
          severity: warning
        - name: exported
          severity: warning
        - name: unexported-return
          severity: warning
        - name: error-strings
          severity: warning
        - name: error-naming
          severity: warning
