version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: employee-management-db
    environment:
      POSTGRES_DB: employee_management
      POSTGRES_USER: employeemgmt
      POSTGRES_PASSWORD: employeemgmt_password
      POSTGRES_INITDB_ARGS: "--auth-host=md5"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    networks:
      - employee-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U employeemgmt -d employee_management"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: employee-management-cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - employee-network
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  employee-network:
    driver: bridge